name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '10.x.x'
        dotnet-quality: 'preview'

    - name: Build with dotnet
      run: dotnet build --configuration Release .\\src\\Blazor-Analytics.sln
  
    - name: Test with dotnet
      run: dotnet test .\\src\\Blazor-Analytics.sln

    - name: Pack with dotnet
      run: dotnet pack --configuration Release .\\src\\Blazor-Analytics.sln
