name: Release

on:
  release:
    types: [published]
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: preview

    - name: Build with dotnet
      run: dotnet build --configuration Release .\\src\\Blazor-Analytics.sln
  
    - name: Test with dotnet
      run: dotnet test .\\src\\Blazor-Analytics.sln

    - name: Pack with dotnet
      run: dotnet pack --configuration Release .\\src\\Blazor-Analytics.sln

    - name: Push package to NuGet
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
